#!/usr/bin/env bash
# USB cottage adapter. Verify pin + checksums, unpack an optional tarball,
# then call the Linux SoT installer (deploy/install.sh).
# Does not enable units, invent users, or bake secrets.
set -euo pipefail

ROLE_DIR=$(cd "$(dirname "$0")" && pwd)
VERSION_FILE="${ROLE_DIR}/VERSION"
SUMS_FILE="${ROLE_DIR}/SHA256SUMS"
TARBALL="${AIMMUNE_TARBALL:-${ROLE_DIR}/aimmune-cottage.tgz}"

usage() {
  cat <<'EOF'
AImmune USB cottage installer (adapter → deploy/install.sh)

  ./install.sh              verify pin/sums, unpack if needed, call Linux SoT
  ./install.sh --verify     VERSION + SHA256SUMS only
  ./install.sh --write-sums regenerate SHA256SUMS for files present in this role

Env:
  AIMMUNE_REPO_ROOT     existing checkout (skips tarball unpack)
  AIMMUNE_TARBALL       tarball path (default: ./aimmune-cottage.tgz)
  AIMMUNE_UNPACK_DIR    unpack destination (default: mktemp)
  DEST_SYSTEMD / DEST_ENV_DIR / DEST_STATE_DIR   forwarded to deploy/install.sh
  AIMMUNE_USB_SKIP_PIP  default 1 — pip stays a next step (same as SoT)

Never put HM_SITE_TOKEN or AIMMUNE_UI_TOKEN on the stick.
EOF
}

die() { echo "ERROR: $*" >&2; exit 1; }

sha256_file() {
  local path=$1
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${path}" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "${path}" | awk '{print $1}'
  else
    python3 -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],"rb").read()).hexdigest())' "${path}"
  fi
}

load_version() {
  [[ -f "${VERSION_FILE}" ]] || die "missing ${VERSION_FILE}"
  # shellcheck disable=SC1090
  PRODUCT= PACKAGE= VERSION= REPO= IFACE_PIN=
  set -a
  # shellcheck disable=SC1090
  source "${VERSION_FILE}"
  set +a
  [[ -n "${IFACE_PIN:-}" ]] || die "VERSION missing IFACE_PIN"
  [[ "${PRODUCT:-}" == "AImmune" ]] || die "VERSION PRODUCT must be AImmune"
}

refuse_secrets() {
  local f
  while IFS= read -r -d '' f; do
    if grep -E -q '^(HM_SITE_TOKEN|AIMMUNE_UI_TOKEN)=.+' "${f}"; then
      die "refusing secret assignment in ${f} — tokens stay off the stick"
    fi
    if grep -E -q 'hm_site_[A-Za-z0-9]{8,}' "${f}"; then
      die "refusing baked hm_site_ token in ${f}"
    fi
  done < <(find "${ROLE_DIR}" -maxdepth 1 -type f -print0)
}

write_sums() {
  local out="${SUMS_FILE}"
  local name
  {
    echo "# AImmune USB cottage checksums. Regenerated by install.sh --write-sums."
    echo "# sha256sum --ignore-missing skips files not on this stick (e.g. tarball)."
    echo "# Do not list secrets. Optional tarball: aimmune-cottage.tgz"
    for name in VERSION README.md install.sh; do
      if [[ -f "${ROLE_DIR}/${name}" ]]; then
        printf '%s  %s\n' "$(sha256_file "${ROLE_DIR}/${name}")" "${name}"
      fi
    done
    if [[ -f "${TARBALL}" ]]; then
      printf '%s  %s\n' "$(sha256_file "${TARBALL}")" "$(basename "${TARBALL}")"
    fi
  } > "${out}"
  echo "wrote ${out}"
}

verify_sums() {
  [[ -f "${SUMS_FILE}" ]] || die "missing ${SUMS_FILE}"
  local line hash name path got
  while IFS= read -r line || [[ -n "${line}" ]]; do
    [[ -z "${line}" || "${line}" == \#* ]] && continue
    hash=${line%%  *}
    name=${line#*  }
    [[ -n "${hash}" && -n "${name}" && "${hash}" != "${line}" ]] || die "bad SHA256SUMS line: ${line}"
    path="${ROLE_DIR}/${name}"
    if [[ ! -f "${path}" ]]; then
      echo "  skip missing ${name} (not on this stick)"
      continue
    fi
    got=$(sha256_file "${path}")
    [[ "${got}" == "${hash}" ]] || die "checksum mismatch for ${name}"
    echo "  ok ${name}"
  done < "${SUMS_FILE}"
}

find_repo_root() {
  if [[ -n "${AIMMUNE_REPO_ROOT:-}" ]]; then
    [[ -f "${AIMMUNE_REPO_ROOT}/deploy/install.sh" ]] || die "AIMMUNE_REPO_ROOT missing deploy/install.sh"
    echo "${AIMMUNE_REPO_ROOT}"
    return
  fi
  local walk=${ROLE_DIR}
  local i
  for i in 1 2 3 4 5 6; do
    if [[ -f "${walk}/deploy/install.sh" ]]; then
      echo "${walk}"
      return
    fi
    walk=$(cd "${walk}/.." && pwd)
  done
  if [[ -f "${TARBALL}" ]]; then
    local dest=${AIMMUNE_UNPACK_DIR:-}
    if [[ -z "${dest}" ]]; then
      dest=$(mktemp -d "${TMPDIR:-/tmp}/aimmune-usb-XXXXXX")
    fi
    mkdir -p "${dest}"
    echo "unpacking ${TARBALL} → ${dest}" >&2
    tar -xzf "${TARBALL}" -C "${dest}"
    if [[ -f "${dest}/deploy/install.sh" ]]; then
      echo "${dest}"
      return
    fi
    if [[ -f "${dest}/auto-defense/deploy/install.sh" ]]; then
      echo "${dest}/auto-defense"
      return
    fi
    die "tarball unpacked but deploy/install.sh not found under ${dest}"
  fi
  die "no checkout, no AIMMUNE_REPO_ROOT, no ${TARBALL}"
}

verify_iface_pin() {
  local root=$1
  if [[ -f "${root}/.gitmodules" ]]; then
    grep -q 'vendor/inference-iface' "${root}/.gitmodules" \
      || die "checkout missing vendor/inference-iface in .gitmodules"
  fi
  if command -v git >/dev/null 2>&1 && [[ -d "${root}/.git" || -f "${root}/.git" ]]; then
    local pin
    pin=$(git -C "${root}" submodule status -- vendor/inference-iface 2>/dev/null | awk '{print $1}' | tr -d '-+' || true)
    if [[ -n "${pin}" && "${pin}" != "${IFACE_PIN}" ]]; then
      die "iface pin ${pin} != VERSION IFACE_PIN ${IFACE_PIN}"
    fi
  fi
}

call_linux_sot() {
  local root=$1
  local installer="${root}/deploy/install.sh"
  [[ -f "${installer}" ]] || die "missing ${installer}"
  echo "calling Linux SoT: ${installer}"
  # shellcheck disable=SC2068
  "${installer}"
}

# --- main -----------------------------------------------------------------
ACTION=install
case "${1:-}" in
  -h|--help) usage; exit 0 ;;
  --verify) ACTION=verify ;;
  --write-sums) ACTION=write-sums ;;
  "") ACTION=install ;;
  *) die "unknown arg: $1 (try --help)" ;;
esac

echo "AImmune USB cottage adapter"
echo "  role: ${ROLE_DIR}"

refuse_secrets
load_version
echo "  pin:  ${PACKAGE} ${VERSION}  iface ${IFACE_PIN}"

if [[ "${ACTION}" == "write-sums" ]]; then
  write_sums
  exit 0
fi

verify_sums

if [[ "${ACTION}" == "verify" ]]; then
  echo "USB cottage verify ok"
  exit 0
fi

REPO_ROOT=$(find_repo_root)
echo "  repo: ${REPO_ROOT}"
verify_iface_pin "${REPO_ROOT}"

if [[ "${AIMMUNE_USB_SKIP_PIP:-1}" != "1" ]]; then
  python3 -m pip install -e "${REPO_ROOT}"
fi

call_linux_sot "${REPO_ROOT}"
